use_frameworks!

target 'Reqres_Example' do
    pod 'Reqres', :path => '../'
    pod 'Alamofire'
    
    target 'Reqres_Tests' do
        inherit! :search_paths
        
        pod 'Quick', '~> 0.10'
        pod 'Nimble', '~> 5.0'
    end
end
