osx_image: xcode11.2
language: objective-c
cache:
  directories:
  - Carthage
  - .build
env:
  global:
  - FRAMEWORK_NAME=Reqres
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- carthage bootstrap --platform iOS --cache-builds
before_deploy:
- carthage build --no-skip-current --platform iOS --cache-builds
- carthage archive $FRAMEWORK_NAME
after_deploy:
- pod trunk push
script:
- set -o pipefail && xcodebuild test -scheme Reqres -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.2' ONLY_ACTIVE_ARCH=YES | xcpretty
- swift build
- pod lib lint
deploy:
  provider: releases
  api_key:
    secure: fLdK+WsGAXajnI6BVNjthNyXx+v+YihXAtZNO85LdA2p8o4OthlXCivdpby4VbFwMxI/JXAnNJSygYNDULwkdower43MwBurXenj45MWRyJ3dkSbG2Aqd0Qtb1CEu2Djm/MuOJ2Nz60MqWtC2blqZf7XbxDH5Bbq2wNGYnrktxWGDhUaNHJumSLdg5y6xbC+H5NGeXONXHfTJhVOrvzvYEAkYoKPk34P01BPUF6HPyCqcwzixpkhYcnsgckgBu1JMUlTJR5aiTNwLjPxbyI5Q/2VuUX8Ma7W7Wv0rVcwGAQae/eJHE5cuNNLJOxvX9CnhxbOhmf5Vq7dLy94aKdDhcSujcPt3ue7jJMuqf2kKR1IlURVYEFBp8wi49d8W+J/WeFEzPeL6ZsURsg6N2IvNjGjcnIgf6oIwUmWVPFlFWar2/QN03N1KVS+Ihn8qhu5BxtV9dm6teYaYdVU4v5rHniwg+TbxsalqkHG3JubP+WutSm9QHz/cFERWEh6PAbnVask2Nmho8h9NQOomv/1zJzu/QaAZcjZ6OxzYKDdVuem71dyqi5cO8AzD9HGbDo6RkRjTjVjTkCgnc2GjmfgElp8fhuLGdJzQS/o7vQgSIY9iYiFHb4XT122rzHJf91RoLNNhUQw+K6NgBBuhSYVAgYV6e0KnbgxgJWZi+fP3QI=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: AckeeCZ/Reqres
    tags: true
