name: Tests

on: [pull_request, push]

jobs:
  tests:
    name: Run tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: AckeeCZ/load-xcode-version@1.1.0
      - name: Run tests
        run: swift test